### ISSUE TITLE
Calendar Naming changes

### ISSUE THREAD

**Issue by Aashish-Kambala** [DallasFormulaRacing/DFRWebsite#154]
Change IC Marketing to Marketing
Change IC Business to Business
Change IC Composites to Composites
Add EV General Meeting 5:30 Wednesdays
Combine IC and EV Manufacturing meetings
Combine IC and EV Ergo

**Comment by Fernando4242** [comment]
@Aashish-Kambala Thanks Aashish for that will work on it soon!
